[package]
name = "game"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Troels \"Sheepyhead\" Jessen"]
edition = "2021"

[dependencies]
bevy = "0.11"
lib ={ path = "../lib", version = "0.1"}