[workspace]
resolver = "2"

members = [
    "game", 
    "lib", 
    "macros", 
    "tools/ci"
]

default-members = ["game","lib"]

# Enable max dependenacy optimizations without impacting release compiles
[profile.dev.package."*"]
opt-level = 3